import Head from "next/head";

import Navbar from "@/components/Navbar";
import Jumbotron from "@/components/Jumbotron";
import Slider from "@/components/Slider";
import Card from "@/components/Card";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Elemes ID</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Jumbotron />
      <Slider />
      <Card />
      <Footer />
    </>
  );
}
